/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as GroupsGroupIdExpensesRouteImport } from './routes/groups/$groupId/expenses';
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index';
import { Route as GroupsGroupIdMembersRouteImport } from './routes/groups/$groupId/members';
import { Route as GroupsGroupIdRouteRouteImport } from './routes/groups/$groupId/route';
import { Route as GroupsGroupIdSummaryRouteImport } from './routes/groups/$groupId/summary';
import { Route as GroupsCreateRouteImport } from './routes/groups/create';
import { Route as GroupsExpenseRouteImport } from './routes/groups/expense';
import { Route as GroupsIndexRouteImport } from './routes/groups/index';
import { Route as GroupsJoinRouteImport } from './routes/groups/join';
import { Route as GroupsRouteRouteImport } from './routes/groups/route';
import { Route as GroupsScanRouteImport } from './routes/groups/scan';
import { Route as IndexRouteImport } from './routes/index';

const GroupsRouteRoute = GroupsRouteRouteImport.update({
	id: '/groups',
	path: '/groups',
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: '/',
	path: '/',
	getParentRoute: () => rootRouteImport,
} as any);
const GroupsIndexRoute = GroupsIndexRouteImport.update({
	id: '/',
	path: '/',
	getParentRoute: () => GroupsRouteRoute,
} as any);
const GroupsScanRoute = GroupsScanRouteImport.update({
	id: '/scan',
	path: '/scan',
	getParentRoute: () => GroupsRouteRoute,
} as any);
const GroupsJoinRoute = GroupsJoinRouteImport.update({
	id: '/join',
	path: '/join',
	getParentRoute: () => GroupsRouteRoute,
} as any);
const GroupsExpenseRoute = GroupsExpenseRouteImport.update({
	id: '/expense',
	path: '/expense',
	getParentRoute: () => GroupsRouteRoute,
} as any);
const GroupsCreateRoute = GroupsCreateRouteImport.update({
	id: '/create',
	path: '/create',
	getParentRoute: () => GroupsRouteRoute,
} as any);
const GroupsGroupIdRouteRoute = GroupsGroupIdRouteRouteImport.update({
	id: '/$groupId',
	path: '/$groupId',
	getParentRoute: () => GroupsRouteRoute,
} as any);
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
	id: '/',
	path: '/',
	getParentRoute: () => GroupsGroupIdRouteRoute,
} as any);
const GroupsGroupIdSummaryRoute = GroupsGroupIdSummaryRouteImport.update({
	id: '/summary',
	path: '/summary',
	getParentRoute: () => GroupsGroupIdRouteRoute,
} as any);
const GroupsGroupIdMembersRoute = GroupsGroupIdMembersRouteImport.update({
	id: '/members',
	path: '/members',
	getParentRoute: () => GroupsGroupIdRouteRoute,
} as any);
const GroupsGroupIdExpensesRoute = GroupsGroupIdExpensesRouteImport.update({
	id: '/expenses',
	path: '/expenses',
	getParentRoute: () => GroupsGroupIdRouteRoute,
} as any);

export interface FileRoutesByFullPath {
	'/': typeof IndexRoute;
	'/groups': typeof GroupsRouteRouteWithChildren;
	'/groups/$groupId': typeof GroupsGroupIdRouteRouteWithChildren;
	'/groups/create': typeof GroupsCreateRoute;
	'/groups/expense': typeof GroupsExpenseRoute;
	'/groups/join': typeof GroupsJoinRoute;
	'/groups/scan': typeof GroupsScanRoute;
	'/groups/': typeof GroupsIndexRoute;
	'/groups/$groupId/expenses': typeof GroupsGroupIdExpensesRoute;
	'/groups/$groupId/members': typeof GroupsGroupIdMembersRoute;
	'/groups/$groupId/summary': typeof GroupsGroupIdSummaryRoute;
	'/groups/$groupId/': typeof GroupsGroupIdIndexRoute;
}
export interface FileRoutesByTo {
	'/': typeof IndexRoute;
	'/groups/create': typeof GroupsCreateRoute;
	'/groups/expense': typeof GroupsExpenseRoute;
	'/groups/join': typeof GroupsJoinRoute;
	'/groups/scan': typeof GroupsScanRoute;
	'/groups': typeof GroupsIndexRoute;
	'/groups/$groupId/expenses': typeof GroupsGroupIdExpensesRoute;
	'/groups/$groupId/members': typeof GroupsGroupIdMembersRoute;
	'/groups/$groupId/summary': typeof GroupsGroupIdSummaryRoute;
	'/groups/$groupId': typeof GroupsGroupIdIndexRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	'/': typeof IndexRoute;
	'/groups': typeof GroupsRouteRouteWithChildren;
	'/groups/$groupId': typeof GroupsGroupIdRouteRouteWithChildren;
	'/groups/create': typeof GroupsCreateRoute;
	'/groups/expense': typeof GroupsExpenseRoute;
	'/groups/join': typeof GroupsJoinRoute;
	'/groups/scan': typeof GroupsScanRoute;
	'/groups/': typeof GroupsIndexRoute;
	'/groups/$groupId/expenses': typeof GroupsGroupIdExpensesRoute;
	'/groups/$groupId/members': typeof GroupsGroupIdMembersRoute;
	'/groups/$groupId/summary': typeof GroupsGroupIdSummaryRoute;
	'/groups/$groupId/': typeof GroupsGroupIdIndexRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| '/'
		| '/groups'
		| '/groups/$groupId'
		| '/groups/create'
		| '/groups/expense'
		| '/groups/join'
		| '/groups/scan'
		| '/groups/'
		| '/groups/$groupId/expenses'
		| '/groups/$groupId/members'
		| '/groups/$groupId/summary'
		| '/groups/$groupId/';
	fileRoutesByTo: FileRoutesByTo;
	to:
		| '/'
		| '/groups/create'
		| '/groups/expense'
		| '/groups/join'
		| '/groups/scan'
		| '/groups'
		| '/groups/$groupId/expenses'
		| '/groups/$groupId/members'
		| '/groups/$groupId/summary'
		| '/groups/$groupId';
	id:
		| '__root__'
		| '/'
		| '/groups'
		| '/groups/$groupId'
		| '/groups/create'
		| '/groups/expense'
		| '/groups/join'
		| '/groups/scan'
		| '/groups/'
		| '/groups/$groupId/expenses'
		| '/groups/$groupId/members'
		| '/groups/$groupId/summary'
		| '/groups/$groupId/';
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	GroupsRouteRoute: typeof GroupsRouteRouteWithChildren;
}

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/groups': {
			id: '/groups';
			path: '/groups';
			fullPath: '/groups';
			preLoaderRoute: typeof GroupsRouteRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		'/': {
			id: '/';
			path: '/';
			fullPath: '/';
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		'/groups/': {
			id: '/groups/';
			path: '/';
			fullPath: '/groups/';
			preLoaderRoute: typeof GroupsIndexRouteImport;
			parentRoute: typeof GroupsRouteRoute;
		};
		'/groups/scan': {
			id: '/groups/scan';
			path: '/scan';
			fullPath: '/groups/scan';
			preLoaderRoute: typeof GroupsScanRouteImport;
			parentRoute: typeof GroupsRouteRoute;
		};
		'/groups/join': {
			id: '/groups/join';
			path: '/join';
			fullPath: '/groups/join';
			preLoaderRoute: typeof GroupsJoinRouteImport;
			parentRoute: typeof GroupsRouteRoute;
		};
		'/groups/expense': {
			id: '/groups/expense';
			path: '/expense';
			fullPath: '/groups/expense';
			preLoaderRoute: typeof GroupsExpenseRouteImport;
			parentRoute: typeof GroupsRouteRoute;
		};
		'/groups/create': {
			id: '/groups/create';
			path: '/create';
			fullPath: '/groups/create';
			preLoaderRoute: typeof GroupsCreateRouteImport;
			parentRoute: typeof GroupsRouteRoute;
		};
		'/groups/$groupId': {
			id: '/groups/$groupId';
			path: '/$groupId';
			fullPath: '/groups/$groupId';
			preLoaderRoute: typeof GroupsGroupIdRouteRouteImport;
			parentRoute: typeof GroupsRouteRoute;
		};
		'/groups/$groupId/': {
			id: '/groups/$groupId/';
			path: '/';
			fullPath: '/groups/$groupId/';
			preLoaderRoute: typeof GroupsGroupIdIndexRouteImport;
			parentRoute: typeof GroupsGroupIdRouteRoute;
		};
		'/groups/$groupId/summary': {
			id: '/groups/$groupId/summary';
			path: '/summary';
			fullPath: '/groups/$groupId/summary';
			preLoaderRoute: typeof GroupsGroupIdSummaryRouteImport;
			parentRoute: typeof GroupsGroupIdRouteRoute;
		};
		'/groups/$groupId/members': {
			id: '/groups/$groupId/members';
			path: '/members';
			fullPath: '/groups/$groupId/members';
			preLoaderRoute: typeof GroupsGroupIdMembersRouteImport;
			parentRoute: typeof GroupsGroupIdRouteRoute;
		};
		'/groups/$groupId/expenses': {
			id: '/groups/$groupId/expenses';
			path: '/expenses';
			fullPath: '/groups/$groupId/expenses';
			preLoaderRoute: typeof GroupsGroupIdExpensesRouteImport;
			parentRoute: typeof GroupsGroupIdRouteRoute;
		};
	}
}

interface GroupsGroupIdRouteRouteChildren {
	GroupsGroupIdExpensesRoute: typeof GroupsGroupIdExpensesRoute;
	GroupsGroupIdMembersRoute: typeof GroupsGroupIdMembersRoute;
	GroupsGroupIdSummaryRoute: typeof GroupsGroupIdSummaryRoute;
	GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute;
}

const GroupsGroupIdRouteRouteChildren: GroupsGroupIdRouteRouteChildren = {
	GroupsGroupIdExpensesRoute: GroupsGroupIdExpensesRoute,
	GroupsGroupIdMembersRoute: GroupsGroupIdMembersRoute,
	GroupsGroupIdSummaryRoute: GroupsGroupIdSummaryRoute,
	GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
};

const GroupsGroupIdRouteRouteWithChildren =
	GroupsGroupIdRouteRoute._addFileChildren(GroupsGroupIdRouteRouteChildren);

interface GroupsRouteRouteChildren {
	GroupsGroupIdRouteRoute: typeof GroupsGroupIdRouteRouteWithChildren;
	GroupsCreateRoute: typeof GroupsCreateRoute;
	GroupsExpenseRoute: typeof GroupsExpenseRoute;
	GroupsJoinRoute: typeof GroupsJoinRoute;
	GroupsScanRoute: typeof GroupsScanRoute;
	GroupsIndexRoute: typeof GroupsIndexRoute;
}

const GroupsRouteRouteChildren: GroupsRouteRouteChildren = {
	GroupsGroupIdRouteRoute: GroupsGroupIdRouteRouteWithChildren,
	GroupsCreateRoute: GroupsCreateRoute,
	GroupsExpenseRoute: GroupsExpenseRoute,
	GroupsJoinRoute: GroupsJoinRoute,
	GroupsScanRoute: GroupsScanRoute,
	GroupsIndexRoute: GroupsIndexRoute,
};

const GroupsRouteRouteWithChildren = GroupsRouteRoute._addFileChildren(
	GroupsRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	GroupsRouteRoute: GroupsRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();
